USE customer;
SELECT * FROM customer_shopping_behavior;

-- Q1: Total revenue generated by male vs female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_shopping_behavior
GROUP BY gender;

-- Q2: Which customers used the discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customer_shopping_behavior
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_shopping_behavior);
            
-- Q2.1: To count the number of customers for query 2.
SELECT 
    COUNT(*) AS total_customers_meeting_criteria
FROM
    customer_shopping_behavior
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_shopping_behavior);
            
-- Q3: Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, ROUND(AVG(review_rating), 2) AS top_products
FROM
    customer_shopping_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4: Compare the average purchase amounts between standard and express shipping? 
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS 'Average Purchase Amount'
FROM
    customer_shopping_behavior
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5: Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 
SELECT 
    subscription_status,
    COUNT(customer_id) AS 'Number of Customers',
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer_shopping_behavior
GROUP BY subscription_status
ORDER BY average_spend DESC;

-- Q6: Which 5 products have the highest percentage of purchases with discounts applied? 
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS product_percentage
FROM
    customer_shopping_behavior
GROUP BY item_purchased
ORDER BY product_percentage DESC
LIMIT 5;

-- Q7: Segment customers into New, Returning, and Loyal-based on their total number of previous purchases, and show the count of each segment. 
WITH customers AS
	(SELECT previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'new_customers'
		WHEN previous_purchases BETWEEN 2 AND 7 THEN 'returning_customers'
		Else 'loyal_customers' END AS customer_segment
	FROM customer_shopping_behavior)

SELECT customer_segment, COUNT(*) AS number_of_customers 
	FROM customers
GROUP BY customer_segment;

-- 	Q8: What are the top 3 most purchased products within each category? 
WITH product_count AS
(SELECT category,
	item_purchased,
	COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_shopping_behavior
GROUP BY 
	category, item_purchased
)
SELECT 
    item_rank, category, item_purchased, total_orders
FROM
    product_count
WHERE
    item_rank <= 3;
    
-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
SELECT 
    subscription_status, COUNT(customer_id) AS potential_buyers
FROM
    customer_shopping_behavior
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10: What is the revenue contribution of the each age group? 
SELECT 
    age_group,
    COUNT(customer_id) AS customers_count,
    ROUND(SUM(purchase_amount), 2) AS revenue_contribution
FROM
    customer_shopping_behavior
GROUP BY age_group
ORDER BY customers_count DESC;
            
            